Caps 82
capstone-signal/backend pull request #18
Opened 2022-04-24 10:14 UTC by Hyun-git

## 티켓

[CAPS-82 회원가입](https://2022springcapstone.atlassian.net/browse/CAPS-82?atlOrigin=eyJpIjoiYmVhMTBjYmY3MWM2NGNkZjkyOTJkNGZmMjU4ZGFhODYiLCJwIjoiaiJ9)

## 작업 내용
- [ ] Github 로그인 로직추가

2022-04-24 13:47 UTC, dghg requested changes
1. **PR 내용 자세하게 올리기 / 코드가 뭔코든지 모르겠음** 
2. 라이브리뷰 컨트롤러는 빼달라 하려다 커밋 꼬일거같아서 패스하겠는데 다음부터는 브랜치 제대로 나눠주세요~
3. 필요없는 println 제거
4. invalid authentication이면 리다이렉트 대신 `403` 리턴 하도록 수정
5. 브랜치 풀받아서 실행해봤는데 컴파일 오류남
6. 전체적으로 패키지 구조 기존 프로젝트에 맞게 수정

나머지는 밑에 코멘트 달았습니다~

2022-04-24 13:47 UTC, dghg commented on build.gradle
> +	implementation 'io.jsonwebtoken:jjwt-api:0.11.1'
51~57L 왜 똑같은 라이브러리가 세번 들어가있나요?

2022-04-24 13:47 UTC, dghg commented on src/main/java/com/hidiscuss/backend/entity/User.java
> -    @Column(name = "email", nullable = false)
`nullable false` 왜 빠졌나요?

2022-04-24 13:47 UTC, dghg commented on src/main/java/com/hidiscuss/backend/oauth/OAuth2SuccessHandler.java
> +            User user = userRequestMapper.toUser(oAuth2User, gitaccessToken, ghEmails2.get(2).getEmail());
왜 `UserRequestMapper` 통해서 생성하나요?

2022-04-24 13:47 UTC, dghg commented on src/main/java/com/hidiscuss/backend/oauth/OAuth2SuccessHandler.java
> +            User user = userRequestMapper.toUser(oAuth2User, gitaccessToken, ghEmails2.get(2).getEmail());
`ghEmails2.get(2).getEmail()` 왜 굳이 두번째 인덱스 가져오나요 ? + 1개밖에 없으면 ?

2022-04-24 13:47 UTC, dghg commented on src/main/java/com/hidiscuss/backend/oauth/controller/AuthController.java
> +            e.printStackTrace();
`Exception` 상위로 던져주기 ~

2022-04-24 13:47 UTC, dghg commented on src/main/java/com/hidiscuss/backend/oauth/controller/TokenController.java
> +    public String failLogin(HttpServletResponse response, HttpServletRequest request){
코드 설명 부탁드립니다 ~

2022-04-24 13:47 UTC, dghg commented on src/main/java/com/hidiscuss/backend/oauth/token/TokenService.java
> +        long tokenPeriod = 1000L * 60L * 10L;
`token` 유효기간 10분 너무 짧지 않나요?

2022-04-24 13:47 UTC, dghg commented on src/main/java/com/hidiscuss/backend/oauth/token/JwtAuthFilter.java
> +        if (token != null && tokenService.verifyToken(token)) {
30~37L 수정 필요해보입니다

2022-04-27 03:07 UTC, Hyun-git commented on src/main/java/com/hidiscuss/backend/entity/User.java
> -    @Column(name = "email", nullable = false)
이전에 디버깅 할때 그랬는데 지금은 추가했습니다.

2022-04-27 03:15 UTC, Hyun-git commented on src/main/java/com/hidiscuss/backend/oauth/OAuth2SuccessHandler.java
> +            User user = userRequestMapper.toUser(oAuth2User, gitaccessToken, ghEmails2.get(2).getEmail());
리스트에 맨 마지막을 가져오게 했습니다.!

2022-04-27 03:16 UTC, Hyun-git commented on src/main/java/com/hidiscuss/backend/oauth/token/TokenService.java
> +        long tokenPeriod = 1000L * 60L * 10L;
음 access라 그랬는데 한 2시간으로 설정해 놓겠습니다!

2022-04-27 11:42 UTC, Hyun-git commented on src/main/java/com/hidiscuss/backend/oauth/controller/TokenController.java
> +    public String failLogin(HttpServletResponse response, HttpServletRequest request){
그 실패하면 여기로 던지려고 했는데 다르게 해볼꼐용

2022-04-27 12:34 UTC, Hyun-git commented on src/main/java/com/hidiscuss/backend/oauth/token/JwtAuthFilter.java
> +        if (token != null && tokenService.verifyToken(token)) {
수정완료했습니다.

2022-04-28 11:41 UTC, dghg reviewed
일단..
1. `JwtAuthFilter` 에서 필터 체이닝 안해줘서 오류남
2. jwt claim에 user pk도 담읍시다
3. `service` 하위 패키지에 `JwtAuthFilter` `OAuth2Attribute`는 딴데로 뺍시다
4. 로그인 안해도  `GET /discussion` 같은 API는 호출할 수 있어야 하는데 어떻게 할까요?

2022-04-28 11:41 UTC, dghg commented on src/main/java/com/hidiscuss/backend/service/JwtAuthFilter.java
> +        Cookie[] cookies = req.getCookies();
`null` 반환하면 어떻게 되나요

2022-04-28 11:41 UTC, dghg commented on src/main/java/com/hidiscuss/backend/service/JwtAuthFilter.java
> +        Claims claims = tokenService.parseJwtToken(refreshToken);
여기서 `refreshToken`이 `null`이면 어떻게 되나요

2022-04-28 11:41 UTC, dghg commented on src/main/java/com/hidiscuss/backend/repository/UserRepository.java
> +    User getByName(String name);
`findBy`로 컨벤션 통일~

2022-04-28 11:41 UTC, dghg commented on src/main/java/com/hidiscuss/backend/service/JwtAuthFilter.java
> +            Authentication auth = new UsernamePasswordAuthenticationToken(name,"");
`UsernamePasswordAuthenticationToken` 클래스 주석 한번 읽어보세요~

2022-05-02 13:57 UTC, merged